// Writes sola.fxc: a SOLA pitch shifter for the FXCore.
//   node test_programs/gen-sola.js
//
// The assembler has no macros, so the two unrolled loops (the near-window
// copy and the correlation) are emitted from here.  Everything else is
// written out once, below, and the numbers come from the same constants.
//
// The design is fv-emu's src/sola.c (see docs/sola-shifter-notes.md there,
// "On the FXCore"): a tap walks a delay line at a constant rate, and before
// it reaches the end of its excursion a second tap is placed where the
// signal best matches, then faded in.  The match is a cross-correlation
// searched one lag per sample, on windows read every fourth sample.

const fs = require('fs');
const path = require('path');

const R = 200;              // search reach, ± samples
const M = 100;              // window points, one per 4 samples (L = 400)
const H = 2 * R + 4;        // ticks from request to splice: one lag per tick
const C = 256;              // crossfade length (must be a power of two)
const E = 1024;             // excursion between the two splice points
const N = H + 32;           // near edge, samples of delay
const F = N + E;            // far edge
const CB = N - H + 1;       // near window's first read, at the request
const PBASE = F - H + R + 2;// far window's first read, at the search's lags
const CSH = 31 - Math.log2(C);
const RING = 2048;

if (PBASE + 4 * M >= RING) throw new Error('ring too small');

const L = [];
const emit = (s = '') => L.push(s);

emit(`; sola.fxc - SOLA pitch shifter, one octave down to one octave up.`);
emit(`; Generated by gen-sola.js; edit that, not this.`);
emit(`;`);
emit(`; POT0_SMTH  pitch, -1 octave at 0, unity at the centre, +1 octave at 1`);
emit(`; POT1_SMTH  mix, dry to wet`);
emit(`;`);
emit(`; A tap walks a ${E}-sample stretch of the delay line at (1 - ratio) samples`);
emit(`; per sample, so what it reads is the input resampled.  ${H} ticks before`);
emit(`; it reaches an end the near window (every fourth of ${4 * M} samples at delay`);
emit(`; ${N}) is copied into MR0..MR${M - 1}, and one lag per tick it is correlated`);
emit(`; against the far window as the delay line drifts past, lags -${R}..+${R}.`);
emit(`; At the splice a second tap starts at the other end, offset by the best`);
emit(`; lag, and fades in over ${C} samples.  Correlation and window energy are`);
emit(`; scored as log2 c - log2 e / 2, ties going to the nominal lag.`);
emit(`;`);
emit(`; MR${M}  best score   MR${M + 1}  best lag   MR${M + 2}  step at the request`);
emit(`; MR${M + 3}  splices     MR${M + 4}  missed     MR${M + 5}  searches   MR${M + 6}  last lag`);
emit();
emit(`.rn   dry   r0`);
emit(`.rn   ratio r1        ; Q16`);
emit(`.rn   step  r2        ; Q16, 1 - ratio: the tap's change of delay per tick`);
emit(`.rn   d_a   r3        ; live tap's delay, 16.16`);
emit(`.rn   d_b   r4        ; fading-in tap's delay, 16.16`);
emit(`.rn   fc    r5        ; fade count, -1 when not fading`);
emit(`.rn   cd    r6        ; ticks to the splice, 0 when none is due`);
emit(`.rn   sj    r7        ; search index 0..${2 * R}, -1 when idle`);
emit(`.rn   e0    r8        ; far window energy, this tick`);
emit(`.rn   e1    r9        ;   and the three before it`);
emit(`.rn   e2    r10`);
emit(`.rn   e3    r11`);
emit(`.rn   t     r12`);
emit(`.rn   u     r13`);
emit(`.rn   v     r14`);
emit(`.rn   w     r15`);
emit();
emit(`.mem  ring  ${RING}`);
emit();
emit(`; ---- input`);
emit(`cpy_cs   dry, in0`);
emit(`wrdel    ring, dry`);
emit();
emit(`; ---- first sample: seat the tap mid-excursion, nothing fading or due`);
emit(`cpy_cs   t, samplecnt`);
emit(`jnz      t, inited`);
emit(`wrdld    d_a, ${N + E / 2}`);
emit(`xor      acc32, acc32`);
emit(`addi     acc32, -1`);
emit(`cpy_cc   fc, acc32`);
emit(`cpy_cc   sj, acc32`);
emit(`inited:`);
emit();
emit(`; ---- pitch: ratio = 2^(2p - 1), by way of 2^(2p - 2) = ratio / 2`);
emit(`cpy_cs   t, pot0_smth`);
emit(`sra      t, 4                ; 2p in S5.26`);
emit(`addsi    acc32, -0.0625      ; - 2.0`);
emit(`addi     acc32, -1           ; stays negative at p = 1`);
emit(`exp2     acc32               ; ratio / 2, S.31`);
emit(`sra      acc32, 14           ; ratio, Q16`);
emit(`cpy_cc   ratio, acc32`);
emit(`wrdld    step, 1`);
emit(`sub      step, ratio`);
emit(`cpy_cc   step, acc32`);
emit();
emit(`; ---- far window energy, a running sum that drifts with the delay line`);
emit(`rddel    t, ring+${PBASE}`);
emit(`multrr   t, t`);
emit(`sra      acc32, 7`);
emit(`cpy_cc   u, acc32`);
emit(`rddel    t, ring+${PBASE + 4 * M}`);
emit(`multrr   t, t`);
emit(`sra      acc32, 7`);
emit(`sub      u, acc32`);
emit(`add      acc32, e3           ; the sum four ticks ago, plus the new point, less the old`);
emit(`cpy_cc   e3, e2`);
emit(`cpy_cc   e2, e1`);
emit(`cpy_cc   e1, e0`);
emit(`cpy_cc   e0, acc32`);
emit();
emit(`; ---- the splice, when the countdown runs out`);
emit(`jz       cd, no_splice`);
emit(`addi     cd, -1`);
emit(`cpy_cc   cd, acc32`);
emit(`jnz      cd, no_splice`);
emit(`cpy_cm   v, mr${M + 1}          ; the best lag`);
emit(`jneg     sj, answered`);
emit(`xor      acc32, acc32        ; the search is still running: take the nominal lag`);
emit(`cpy_cc   v, acc32`);
emit(`addi     acc32, -1`);
emit(`cpy_cc   sj, acc32`);
emit(`cpy_cm   t, mr${M + 4}`);
emit(`addi     t, 1`);
emit(`cpy_mc   mr${M + 4}, acc32`);
emit(`answered:`);
emit(`cpy_mc   mr${M + 6}, v`);
emit(`cpy_cm   t, mr${M + 2}`);
emit(`jneg     t, splice_up`);
emit(`addi     v, ${N}               ; down: the new tap starts at the near edge`);
emit(`jmp      seated`);
emit(`splice_up:`);
emit(`neg      v`);
emit(`addi     acc32, ${F}           ; up: at the far edge`);
emit(`seated:`);
emit(`sl       acc32, 16`);
emit(`cpy_cc   d_b, acc32`);
emit(`xor      acc32, acc32`);
emit(`cpy_cc   fc, acc32`);
emit(`cpy_cm   t, mr${M + 3}`);
emit(`addi     t, 1`);
emit(`cpy_mc   mr${M + 3}, acc32`);
emit(`no_splice:`);
emit();
emit(`; ---- the search: lag sj - ${R}, the far window read where it has drifted to`);
emit(`jneg     sj, no_search`);
emit(`clracc64`);
for (let m = 0; m < M; m++) {
    emit(`cpy_cm   t, mr${m}`);
    emit(`macrd    t, ring+${PBASE + 4 * m}`);
}
emit(`rdacc64u t                   ; c`);
emit(`jneg     t, next_lag         ; no splice on an anti-correlation`);
emit(`jz       t, next_lag`);
emit(`log2     t`);
emit(`cpy_cc   u, acc32`);
emit(`log2     e0`);
emit(`sra      acc32, 1`);
emit(`sub      u, acc32            ; score = log2 c - log2 e / 2`);
emit(`cpy_cc   u, acc32`);
emit(`cpy_cm   t, mr${M}`);
emit(`sub      u, t                ; against the best so far`);
emit(`cpy_cc   v, acc32`);
emit(`addi     sj, -${R + 1}`);
emit(`jneg     acc32, tie_near     ; a lag past the nominal must beat it outright`);
emit(`addi     v, -1`);
emit(`cpy_cc   v, acc32`);
emit(`tie_near:`);
emit(`jneg     v, next_lag`);
emit(`cpy_mc   mr${M}, u`);
emit(`addi     sj, -${R}`);
emit(`cpy_mc   mr${M + 1}, acc32`);
emit(`next_lag:`);
emit(`addi     sj, 1`);
emit(`cpy_cc   sj, acc32`);
emit(`addi     sj, -${2 * R + 1}`);
emit(`jneg     acc32, no_search`);
emit(`xor      acc32, acc32`);
emit(`addi     acc32, -1`);
emit(`cpy_cc   sj, acc32           ; all lags seen`);
emit(`no_search:`);
emit();
emit(`; ---- the request: when the tap will reach its edge in ${H} ticks`);
emit(`jnz      cd, no_req`);
emit(`jgez     fc, no_req`);
emit(`jz       step, no_req`);
emit(`cpy_cc   t, step`);
emit(`jgez     step, step_pos`);
emit(`neg      step`);
emit(`cpy_cc   t, acc32`);
emit(`step_pos:`);
emit(`sl       t, 14`);
emit(`cpy_cc   t, acc32`);
emit(`wrdld    u, ${H}<<5`);
emit(`multrr   t, u`);
emit(`sra      acc32, 4`);
emit(`cpy_cc   u, acc32            ; lead = |step| * ${H}, 16.16`);
emit(`jneg     step, rem_up`);
emit(`wrdld    t, ${F}`);
emit(`sub      t, d_a              ; down: the far edge is ahead`);
emit(`jmp      rem_done`);
emit(`rem_up:`);
emit(`wrdld    t, ${N}`);
emit(`sub      d_a, t              ; up: the near edge`);
emit(`rem_done:`);
emit(`cpy_cc   v, acc32            ; remaining`);
emit(`jneg     v, past_edge`);
emit(`sub      u, v`);
emit(`jneg     acc32, no_req`);
emit(`xor      acc32, acc32`);
emit(`addi     acc32, ${H}`);
emit(`cpy_cc   cd, acc32`);
emit(`cpy_mc   mr${M + 2}, step`);
emit(`xor      acc32, acc32`);
emit(`cpy_cc   sj, acc32           ; the search starts next tick`);
emit(`cpy_mc   mr${M + 1}, acc32`);
emit(`wrdld    t, 0x8000`);
emit(`cpy_mc   mr${M}, t            ; best score = -inf`);
emit(`cpy_cm   t, mr${M + 5}`);
emit(`addi     t, 1`);
emit(`cpy_mc   mr${M + 5}, acc32`);
emit(`; the near window, every fourth sample, scaled by 1/128 to keep the sums in range`);
for (let m = 0; m < M; m++) {
    emit(`rddel    t, ring+${CB + 4 * m}`);
    emit(`sra      t, 7`);
    emit(`cpy_mc   mr${m}, acc32`);
}
emit(`jmp      no_req`);
emit(`past_edge:`);
emit(`; the tap is already past the edge it is walking to (the pitch changed`);
emit(`; mid-grain): splice next tick at the nominal lag, unsearched`);
emit(`xor      acc32, acc32`);
emit(`addi     acc32, 1`);
emit(`cpy_cc   cd, acc32`);
emit(`cpy_mc   mr${M + 2}, step`);
emit(`xor      acc32, acc32`);
emit(`cpy_mc   mr${M + 1}, acc32`);
emit(`no_req:`);
emit();
emit(`; ---- the taps`);
emit(`interp   d_a, ring`);
emit(`cpy_cc   t, acc32            ; a`);
emit(`jneg     fc, one_tap`);
emit(`interp   d_b, ring`);
emit(`sub      acc32, t            ; b - a`);
emit(`cpy_cc   u, acc32`);
emit(`sl       fc, ${CSH}               ; fc / ${C}, S.31`);
emit(`multrr   u, acc32`);
emit(`adds     acc32, t            ; a + (b - a) * fade`);
emit(`cpy_cc   t, acc32`);
emit(`one_tap:`);
emit();
emit(`; ---- advance the taps; the fade done, the new tap is the tap`);
emit(`add      d_a, step`);
emit(`cpy_cc   d_a, acc32`);
emit(`jneg     fc, advanced`);
emit(`add      d_b, step`);
emit(`cpy_cc   d_b, acc32`);
emit(`addi     fc, 1`);
emit(`cpy_cc   fc, acc32`);
emit(`addi     fc, -${C}`);
emit(`jneg     acc32, advanced`);
emit(`cpy_cc   d_a, d_b`);
emit(`xor      acc32, acc32`);
emit(`addi     acc32, -1`);
emit(`cpy_cc   fc, acc32`);
emit(`advanced:`);
emit();
emit(`; ---- mix`);
emit(`cpy_cs   u, pot1_smth`);
emit(`subs     t, dry              ; wet - dry`);
emit(`multrr   acc32, u`);
emit(`adds     acc32, dry`);
emit(`cpy_sc   out0, acc32`);
emit(`cpy_sc   out1, acc32`);
emit();

const out = path.join(__dirname, 'sola.fxc');
fs.writeFileSync(out, L.join('\n'));
console.log(`wrote ${out}: ${L.length} lines`);
